const articles = [
  {
    id: 1,
    title: "I ♥ Javascript",
    content: "This is the content of article 1",
    image: {
      src: "javascript.jpg",
      alt: "I love Javascript",
    },
    link: "#i-love-javascript",
    teaser: "This is the reason why I love Javascript!",
    date: "2021-01-01",
    author: "John Doe",
    tags: [
      {
        id: 1,
        name: "Design",
        bgColor: "#F9F5FF",
        textColor: "#6941C6",
      },
      {
        id: 2,
        name: "Research",
        bgColor: "#EEF4FF",
        textColor: "#3538CD",
      },
      {
        id: 3,
        name: "Presentation",
        bgColor: "#FDF2FA",
        textColor: "#C11574",
      },
    ],
  },
  {
    id: 2,
    title: "CSS is Awesome",
    content: "This is the content of article 2",
    image: "love.jpg",
    teaser: "This is the reason why I love CSS!",
    date: "2021-01-02",
    author: "Jane Doe",
    tags: ["Design", "Research", "Presentation"],
  },
  {
    id: 3,
    title: "HTML is Cool",
    content: "This is the content of article 3",
    image: "nodejs.jpg",
    teaser: "This is the reason why I love HTML!",
    date: "2021-01-03",
    author: "John Doe",
    tags: ["Design", "Research", "Presentation"],
  },
  {
    id: 4,
    title: "React is the Best",
    content: "This is the content of article 4",
    image: "remote.jpg",
    teaser: "This is the reason why I love React!",
    date: "2021-01-04",
    author: "Jane Doe",
    tags: ["Design", "Research", "Presentation"],
  },
];
